const puppeteer = require('puppeteer');
const fs = require('fs');
const path = require('path');

const generatePDF = async (audit, findings) => {
    const browser = await puppeteer.launch({
        headless: 'new',
        args: ['--no-sandbox', '--disable-setuid-sandbox', '--disable-dev-shm-usage']
    });
    const page = await browser.newPage();
    
    const htmlContent = `
        <!DOCTYPE html>
        <html>
        <head>
            <title>Audit Report - ${audit.contract_name}</title>
            <style>
                body { font-family: Arial, sans-serif; padding: 40px; }
                h1 { color: #2563eb; }
                .header { border-bottom: 2px solid #2563eb; margin-bottom: 20px; }
                .finding { margin-bottom: 20px; padding: 15px; border: 1px solid #ddd; border-radius: 5px; }
                .critical { border-left: 5px solid #dc2626; }
                .high { border-left: 5px solid #ea580c; }
                .medium { border-left: 5px solid #ca8a04; }
                .low { border-left: 5px solid #65a30d; }
                .info { border-left: 5px solid #2563eb; }
                pre { background: #f3f4f6; padding: 10px; border-radius: 5px; overflow-x: auto; }
            </style>
        </head>
        <body>
            <div class='header'>
                <h1>Smart Contract Audit Report</h1>
                <p><strong>Contract:</strong> ${audit.contract_name}</p>
                <p><strong>Compiler:</strong> ${audit.compiler_version}</p>
                <p><strong>Lines of Code:</strong> ${audit.lines_of_code}</p>
                <p><strong>Overall Risk Score:</strong> ${audit.overall_risk_score}/100</p>
                <p><strong>Date:</strong> ${audit.created_at}</p>
            </div>
            <h2>Executive Summary</h2>
            <p>This report details the security analysis of the smart contract. A total of ${findings.length} findings were identified.</p>
            <h2>Findings Detail</h2>
            ${findings.map(f => `
                <div class='finding ${f.severity}'>
                    <h3>[${f.severity.toUpperCase()}] ${f.title}</h3>
                    <p><strong>SWC ID:</strong> ${f.swc_id || 'N/A'}</p>
                    <p><strong>Description:</strong> ${f.description}</p>
                    <p><strong>Affected Lines:</strong> ${f.affected_lines.join(', ')}</p>
                    <pre>${f.code_snippet}</pre>
                    <p><strong>Remediation:</strong> ${f.remediation}</p>
                </div>
            `).join('')}
            <div style='margin-top: 40px; text-align: center; color: #6b7280; font-size: 12px;'>
                Generated by AuditAI Chain | Verification Hash: ${audit.blockchain_tx_hash || 'Pending'}
            </div>
        </body>
        </html>
    `;
    
    await page.setContent(htmlContent, { waitUntil: 'networkidle0' });
    
    const reportsDir = path.join(__dirname, '../../data/reports');
    if (!fs.existsSync(reportsDir)) fs.mkdirSync(reportsDir, { recursive: true });
    
    const pdfPath = path.join(reportsDir, `audit-${audit.id}.pdf`);
    await page.pdf({ path: pdfPath, format: 'A4', printBackground: true });
    
    await browser.close();
    return pdfPath;
};

module.exports = { generatePDF };